version: '3.8'

services:
  frontend:
    build:
      context: ./blog-frontend
    ports:
      - '3000:80'
    depends_on:
      - backend

  backend:
    build:
      context: ./blog
    ports:
      - '4000:4000'
    env_file:
      - .env
    # environment:
    #   MYSQL_DATABASE: ${DB_NAME}
    #   MYSQL_PASSWORD: ${DB_PASS}
    #   MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    depends_on:
      - database

  database:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - db_data:/var/lib/mysql


  migration:
    build:
      context: ./blog
    command: ["npm", "run", "migration:run"]
    depends_on:
      - backend
      - database
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}

volumes:
  db_data: